### ISSUE TITLE
[FATAL] App crashes when communication channel is opened

### ISSUE THREAD

**Issue by ahbitaqu** [ls1intum/artemis-android#51]
When I try to open a non-public communication channel with a lock icon on the artemis app, the app expericences a fatal crash. On public channels with the hashtag icon it works just fine.

Steps to reproduce:
1. Open the app
2. Select a course
3. Try to open a channel with a lock icon 
![artemis-issue-1](https://github.com/user-attachments/assets/1480fc55-4e74-471b-aa85-ebdf4767f81c)

Version: 1.0.0-prod (play store)
Device: Pixel 7

**Comment by ahbitaqu** [comment]
My current suspicion is that this bug is somehow depending on the amount of messages posted in the channel, but I unfortunately can't confirm this

**Comment by julian-wls** [comment]
Thank you for your help.
I had the same issue today and I was going to point it out here as well.
I think it is related to the same issue.

**Stack trace**:
```FATAL EXCEPTION: main
Process: de.tum.cit.aet.artemis, PID: 2350
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: metis_post_context.client_post_id, metis_post_context.course_id, metis_post_context.conversation_id, metis_post_context.type (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:974)
at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:814)
at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.kt:42)
at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.kt:51)
at de.tum.informatics.www1.artemis.native_app.feature.metis.shared.db.MetisDao_Impl$18.call(MetisDao_Impl.java:433)
at de.tum.informatics.www1.artemis.native_app.feature.metis.shared.db.MetisDao_Impl$18.call(MetisDao_Impl.java:429)
at androidx.room.CoroutinesRoom$Companion.execute(CoroutinesRoom.kt:56)
at androidx.room.CoroutinesRoom.execute(Unknown Source:2)
at de.tum.informatics.www1.artemis.native_app.feature.metis.shared.db.MetisDao_Impl.insertPostMetisContext(MetisDao_Impl.java:429)
at de.tum.informatics.www1.artemis.native_app.feature.metis.conversation.service.storage.impl.MetisStorageServiceImpl.insertOrUpdateAnswerPost(MetisStorageServiceImpl.kt:566)
at de.tum.informatics.www1.artemis.native_app.feature.metis.conversation.service.storage.impl.MetisStorageServiceImpl.insertOrUpdatePost(MetisStorageServiceImpl.kt:515)
at de.tum.informatics.www1.artemis.native_app.feature.metis.conversation.service.storage.impl.MetisStorageServiceImpl.insertOrUpdateImpl(MetisStorageServiceImpl.kt:192)
at de.tum.informatics.www1.artemis.native_app.feature.metis.conversation.service.storage.impl.MetisStorageServiceImpl.access$insertOrUpdateImpl(MetisStorageServiceImpl.kt:31)
at de.tum.informatics.www1.artemis.native_app.feature.metis.conversation.service.storage.impl.MetisStorageServiceImpl$insertOrUpdatePostsAndRemoveDeletedPosts$2.invokeSuspend(MetisStorageServiceImpl.kt:222)
at de.tum.informatics.www1.artemis.native_app.feature.metis.conversation.service.storage.impl.MetisStorageServiceImpl$insertOrUpdatePostsAndRemoveDeletedPosts$2.invoke(Unknown Source:8)
at de.tum.informatics.www1.artemis.native_app.feature.metis.conversation.service.storage.impl.MetisStorageServiceImpl$insertOrUpdatePostsAndRemoveDeletedPosts$2.invoke(Unknown Source:2)
at androidx.room.RoomDatabaseKt$withTransaction$transactionBlock$1.invokeSuspend(RoomDatabaseExt.kt:62)
at androidx.room.RoomDatabaseKt$withTransaction$transactionBlock$1.invoke(Unknown Source:8)
at androidx.room.RoomDatabaseKt$withTransaction$transactionBlock$1.invoke(Unknown Source:4)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
at androidx.room.RoomDatabaseKt$startTransactionCoroutine$2$1$1.invokeSuspend(RoomDatabaseExt.kt:103)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
at androidx.room.RoomDatabaseKt$startTransactionCoroutine$2$1.run(RoomDatabaseExt.kt:99)
at androidx.room.TransactionExecutor.execute$lambda$1$lambda$0(TransactionExecutor.kt:36)
at androidx.room.TransactionExecutor.$r8$lambda$FZWr2PGmP3sgXLCiri-DCcePXSs(Unknown Source:0)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2a9dac1, Dispatchers.Main.immediate]```

**Comment by ahbitaqu** [comment]
New Hotfixed patched the issue. Fresh install was needed for the changes to take effect though.
